// Server catalog kept in sync with the Recovery System frontend.
const PRODUCTS = [
  {
    id: 'pulse-pro-x',
    slug: 'pulse-pro-x',
    title: 'Pulse Pro X',
    description: 'Massage gun for deep tissue recovery and post-workout relief.',
    price: 89,
    images: ['/img/products/pulse-pro-x.jpg'],
    category: 'recovery',
    brand: 'RECOVERY SYSTEM',
    stock: 20,
  },
  {
    id: 'cerviflex',
    slug: 'cerviflex',
    title: 'CerviFlex',
    description: 'Neck massager designed to release daily tension and stiffness.',
    price: 59,
    images: ['/img/products/cerviflex.jpg'],
    category: 'recovery',
    brand: 'RECOVERY SYSTEM',
    stock: 20,
  },
  {
    id: 'sleepseal',
    slug: 'sleepseal',
    title: 'SleepSeal',
    description: 'Sleep tape to support calmer breathing and deeper rest.',
    price: 29,
    images: ['/img/products/sleepseal.jpg'],
    category: 'sleep',
    brand: 'RECOVERY SYSTEM',
    stock: 20,
  },
  {
    id: 'sleepband-pro',
    slug: 'sleepband-pro',
    title: 'SleepBand Pro',
    description: 'Bluetooth sleep headband with integrated speakers for calming audio and comfortable wear.',
    price: 69,
    images: ['/img/products/sleepband-pro-1.jpg'],
    category: 'sleep',
    brand: 'RECOVERY SYSTEM',
    stock: 20,
  },
  {
    id: 'white-noise-pro',
    slug: 'white-noise-pro',
    title: 'White Noise Pro',
    description: 'Portable sleep sound machine with multiple white-noise profiles and adjustable volume.',
    price: 79,
    images: ['/img/products/white-noise-pro-1.jpg'],
    category: 'sleep',
    brand: 'RECOVERY SYSTEM',
    stock: 20,
  },
  {
    id: 'weighted-mask-pro',
    slug: 'weighted-mask-pro',
    title: 'WeightedMask Pro',
    description: 'Weighted sleep mask designed to block light and provide gentle pressure for deeper sleep.',
    price: 45,
    images: ['/img/products/weighted-mask-pro-1.jpg'],
    category: 'sleep',
    brand: 'RECOVERY SYSTEM',
    stock: 20,
  },
];

export default PRODUCTS;
